version: '3.8'

services:
  mariadb:
    image: bitnami/mariadb:11.3
    container_name: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=cc5308
    volumes:
      - mariadb_data:/bitnami/mariadb
    expose:
      - 3306
    networks:
      - backend

  moodle:
    image: bitnami/moodle:4.5.0
    container_name: moodle
    restart: always
    expose:
      - "8081"
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=moodledb
      - MOODLE_DATABASE_USER=moodleuser
      - MOODLE_DATABASE_PASSWORD=moodlepass
    volumes:
      - moodle_data:/bitnami/moodle
    depends_on:
      - mariadb
    networks:
      - backend

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    expose:
      - "8080"
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wpuser
      - WORDPRESS_DB_PASSWORD=wppass
    depends_on:
      - mariadb
    networks:
      - backend
    
  
  nuxt:
    build: nuxt/mini-web
    container_name: nuxt-docker
    ports: 
      - 8082:8082
    depends_on:
      - mariadb
    networks:
      - backend

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx-proxy
  #   restart: always
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/conf.d:/etc/nginx/conf.d:ro
  #   depends_on:
  #     - moodle
  #     - wordpress
  #     - nuxt
  #   networks:
  #     - backend

  moodle-db-init:
    image: bitnami/mariadb:11.3
    container_name: moodle-db-init
    restart: "no"
    entrypoint: >
      sh -c "
        sleep 10;
        mariadb -hmariadb -uroot -pcc5308 -e \"
          CREATE DATABASE IF NOT EXISTS moodledb;
          CREATE USER IF NOT EXISTS 'moodleuser'@'%' IDENTIFIED BY 'moodlepass';
          GRANT ALL PRIVILEGES ON moodledb.* TO 'moodleuser'@'%';
          FLUSH PRIVILEGES;\"
      "
    depends_on:
      - mariadb
    networks:
      - backend

  wordpress-db-init:
    image: bitnami/mariadb:11.3
    container_name: wordpress-db-init
    restart: "no"
    entrypoint: >
      sh -c "
        sleep 10;
        mariadb -hmariadb -uroot -pcc5308 -e \"
          CREATE DATABASE IF NOT EXISTS wordpress;
          CREATE USER IF NOT EXISTS 'wpuser'@'%' IDENTIFIED BY 'wppass';
          GRANT ALL PRIVILEGES ON wordpress.* TO 'wpuser'@'%';
          FLUSH PRIVILEGES;\"
      "
    depends_on:
      - mariadb
    networks:
      - backend

volumes:
  mariadb_data:
    driver: local
  moodle_data:

networks:
  backend:
    driver: bridge
